export * from "./Home"
export * from "./Design"
export * from "./Feature"
export * from "./Price"
export * from "./Login"
export * from "./Register"
export * from "./Invitation"
export * from "./PageNotFound"